# Generated by Django 5.0.4 on 2024-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_colleges_remove_courses_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='courseschedules',
            name='days',
        ),
        migrations.AddField(
            model_name='courseschedules',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='course_schedules', to='core.day'),
        ),
    ]
